version: "3.1"

services:
    mongodb:
        container_name: mongodb
        image: mongo:4-xenial
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 0000
        volumes:
            - ./.data/mongodb:/data/db
